<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>

		<!-- Отключаем автоматические global using -->
		<ImplicitUsings>disable</ImplicitUsings>

		<!-- Устанавливаем совместимую версию языка -->
		<LangVersion>8.0</LangVersion>

		<!-- Отключаем nullable reference types -->
		<Nullable>disable</Nullable>
	</PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\BepInExLibs\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\GameLibs\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\BepInExLibs\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Harmony">
      <HintPath>..\BepInExLibs\BepInEx.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="ClientNetworkTransform">
      <HintPath>..\GameLibs\ClientNetworkTransform.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Steamworks.Win64">
      <HintPath>..\GameLibs\Facepunch.Steamworks.Win64.dll</HintPath>
    </Reference>
    <Reference Include="Grpc.Core">
      <HintPath>..\GameLibs\Grpc.Core.dll</HintPath>
    </Reference>
    <Reference Include="HarmonyXInterop">
      <HintPath>..\BepInExLibs\HarmonyXInterop.dll</HintPath>
    </Reference>
    <Reference Include="Ionic.Zip.Unity">
      <HintPath>..\GameLibs\Ionic.Zip.Unity.dll</HintPath>
    </Reference>
    <Reference Include="LunarConsole">
      <HintPath>..\GameLibs\LunarConsole.dll</HintPath>
    </Reference>
    <Reference Include="MarcosPereira.PolygonReducer.Runtime">
      <HintPath>..\GameLibs\MarcosPereira.PolygonReducer.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="MarcosPereira.UnityUtilities.Runtime">
      <HintPath>..\GameLibs\MarcosPereira.UnityUtilities.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="MaxSdk.Scripts">
      <HintPath>..\GameLibs\MaxSdk.Scripts.dll</HintPath>
    </Reference>
    <Reference Include="modio.UnityPlugin">
      <HintPath>..\GameLibs\modio.UnityPlugin.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>..\BepInExLibs\Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Mdb">
      <HintPath>..\BepInExLibs\Mono.Cecil.Mdb.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Pdb">
      <HintPath>..\BepInExLibs\Mono.Cecil.Pdb.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Rocks">
      <HintPath>..\BepInExLibs\Mono.Cecil.Rocks.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Security">
      <HintPath>..\GameLibs\Mono.Security.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>..\BepInExLibs\MonoMod.RuntimeDetour.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>..\BepInExLibs\MonoMod.Utils.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\GameLibs\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Purchasing.Common">
      <HintPath>..\GameLibs\Purchasing.Common.dll</HintPath>
    </Reference>
    <Reference Include="sc.vegetationspawner.runtime">
      <HintPath>..\GameLibs\sc.vegetationspawner.runtime.dll</HintPath>
    </Reference>
    <Reference Include="StylizedWaterForURP">
      <HintPath>..\GameLibs\StylizedWaterForURP.dll</HintPath>
    </Reference>
    <Reference Include="unity-websocket-sharp">
      <HintPath>..\GameLibs\unity-websocket-sharp.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>..\GameLibs\Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="Unity.AI.Navigation">
      <HintPath>..\GameLibs\Unity.AI.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="Unity.AI.Navigation.Samples">
      <HintPath>..\GameLibs\Unity.AI.Navigation.Samples.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Barracuda">
      <HintPath>..\GameLibs\Unity.Barracuda.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Barracuda.BurstBLAS">
      <HintPath>..\GameLibs\Unity.Barracuda.BurstBLAS.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Barracuda.ONNX">
      <HintPath>..\GameLibs\Unity.Barracuda.ONNX.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>..\GameLibs\Unity.Burst.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst.Cecil">
      <HintPath>..\GameLibs\Unity.Burst.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst.Cecil.Mdb">
      <HintPath>..\GameLibs\Unity.Burst.Cecil.Mdb.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst.Cecil.Pdb">
      <HintPath>..\GameLibs\Unity.Burst.Cecil.Pdb.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst.Cecil.Rocks">
      <HintPath>..\GameLibs\Unity.Burst.Cecil.Rocks.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst.Unsafe">
      <HintPath>..\GameLibs\Unity.Burst.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>..\GameLibs\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections.LowLevel.ILSupport">
      <HintPath>..\GameLibs\Unity.Collections.LowLevel.ILSupport.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\GameLibs\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ML-Agents">
      <HintPath>..\GameLibs\Unity.ML-Agents.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ML-Agents.CommunicatorObjects">
      <HintPath>..\GameLibs\Unity.ML-Agents.CommunicatorObjects.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Samples.Utilities">
      <HintPath>..\GameLibs\Unity.Multiplayer.Samples.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Samples.Utilities.ClientAuthority">
      <HintPath>..\GameLibs\Unity.Multiplayer.Samples.Utilities.ClientAuthority.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Samples.Utilities.RNSM">
      <HintPath>..\GameLibs\Unity.Multiplayer.Samples.Utilities.RNSM.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.Adapters">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.Adapters.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.Adapters.Ngo1">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.Adapters.Ngo1.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.Common">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.Common.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.Initialization">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.Initialization.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.MetricEvents">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.MetricEvents.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.MetricTestData">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.MetricTestData.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.MetricTypes">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.MetricTypes.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.NetStats">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.NetStats.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.NetStatsMonitor.Component">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.NetStatsMonitor.Component.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.NetStatsMonitor.Configuration">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.NetStatsMonitor.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.NetStatsMonitor.Implementation">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.NetStatsMonitor.Implementation.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.NetStatsReporting">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.NetStatsReporting.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.NetworkProfiler.Runtime">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.NetworkProfiler.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.NetworkSolutionInterface">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.NetworkSolutionInterface.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Multiplayer.Tools.Util">
      <HintPath>..\GameLibs\Unity.Multiplayer.Tools.Util.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Netcode.Components">
      <HintPath>..\GameLibs\Unity.Netcode.Components.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Netcode.Runtime">
      <HintPath>..\GameLibs\Unity.Netcode.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Networking.Transport">
      <HintPath>..\GameLibs\Unity.Networking.Transport.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder">
      <HintPath>..\GameLibs\Unity.ProBuilder.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder.Csg">
      <HintPath>..\GameLibs\Unity.ProBuilder.Csg.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder.KdTree">
      <HintPath>..\GameLibs\Unity.ProBuilder.KdTree.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder.Poly2Tri">
      <HintPath>..\GameLibs\Unity.ProBuilder.Poly2Tri.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder.Stl">
      <HintPath>..\GameLibs\Unity.ProBuilder.Stl.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Profiling.Core">
      <HintPath>..\GameLibs\Unity.Profiling.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RemoteConfig">
      <HintPath>..\GameLibs\Unity.RemoteConfig.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary">
      <HintPath>..\GameLibs\Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>..\GameLibs\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.ShaderLibrary">
      <HintPath>..\GameLibs\Unity.RenderPipelines.Core.ShaderLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary">
      <HintPath>..\GameLibs\Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.2D.Runtime">
      <HintPath>..\GameLibs\Unity.RenderPipelines.Universal.2D.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>..\GameLibs\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Shaders">
      <HintPath>..\GameLibs\Unity.RenderPipelines.Universal.Shaders.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>..\GameLibs\Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ScriptableBuildPipeline">
      <HintPath>..\GameLibs\Unity.ScriptableBuildPipeline.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Analytics">
      <HintPath>..\GameLibs\Unity.Services.Analytics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Authentication">
      <HintPath>..\GameLibs\Unity.Services.Authentication.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.CloudSave">
      <HintPath>..\GameLibs\Unity.Services.CloudSave.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core">
      <HintPath>..\GameLibs\Unity.Services.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Analytics">
      <HintPath>..\GameLibs\Unity.Services.Core.Analytics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Configuration">
      <HintPath>..\GameLibs\Unity.Services.Core.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Device">
      <HintPath>..\GameLibs\Unity.Services.Core.Device.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Environments">
      <HintPath>..\GameLibs\Unity.Services.Core.Environments.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Environments.Internal">
      <HintPath>..\GameLibs\Unity.Services.Core.Environments.Internal.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Internal">
      <HintPath>..\GameLibs\Unity.Services.Core.Internal.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Networking">
      <HintPath>..\GameLibs\Unity.Services.Core.Networking.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Registration">
      <HintPath>..\GameLibs\Unity.Services.Core.Registration.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Scheduler">
      <HintPath>..\GameLibs\Unity.Services.Core.Scheduler.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Telemetry">
      <HintPath>..\GameLibs\Unity.Services.Core.Telemetry.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Core.Threading">
      <HintPath>..\GameLibs\Unity.Services.Core.Threading.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Lobbies">
      <HintPath>..\GameLibs\Unity.Services.Lobbies.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.QoS">
      <HintPath>..\GameLibs\Unity.Services.QoS.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Relay">
      <HintPath>..\GameLibs\Unity.Services.Relay.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Services.Wire.Internal">
      <HintPath>..\GameLibs\Unity.Services.Wire.Internal.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Subsystem.Registration">
      <HintPath>..\GameLibs\Unity.Subsystem.Registration.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TerrainTools">
      <HintPath>..\GameLibs\Unity.TerrainTools.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\GameLibs\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Timeline">
      <HintPath>..\GameLibs\Unity.Timeline.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Tutorials.Core">
      <HintPath>..\GameLibs\Unity.Tutorials.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.Antlr3.Runtime">
      <HintPath>..\GameLibs\Unity.VisualScripting.Antlr3.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.Core">
      <HintPath>..\GameLibs\Unity.VisualScripting.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.Flow">
      <HintPath>..\GameLibs\Unity.VisualScripting.Flow.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.State">
      <HintPath>..\GameLibs\Unity.VisualScripting.State.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.Management">
      <HintPath>..\GameLibs\Unity.XR.Management.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\GameLibs\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AccessibilityModule">
      <HintPath>..\GameLibs\UnityEngine.AccessibilityModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>..\GameLibs\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AndroidJNIModule">
      <HintPath>..\GameLibs\UnityEngine.AndroidJNIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\GameLibs\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ARModule">
      <HintPath>..\GameLibs\UnityEngine.ARModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\GameLibs\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\GameLibs\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClothModule">
      <HintPath>..\GameLibs\UnityEngine.ClothModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClusterInputModule">
      <HintPath>..\GameLibs\UnityEngine.ClusterInputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClusterRendererModule">
      <HintPath>..\GameLibs\UnityEngine.ClusterRendererModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CommandStateObserverModule">
      <HintPath>..\GameLibs\UnityEngine.CommandStateObserverModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ContentLoadModule">
      <HintPath>..\GameLibs\UnityEngine.ContentLoadModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\GameLibs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CrashReportingModule">
      <HintPath>..\GameLibs\UnityEngine.CrashReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>..\GameLibs\UnityEngine.DirectorModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DSPGraphModule">
      <HintPath>..\GameLibs\UnityEngine.DSPGraphModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GameCenterModule">
      <HintPath>..\GameLibs\UnityEngine.GameCenterModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GIModule">
      <HintPath>..\GameLibs\UnityEngine.GIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GraphToolsFoundationModule">
      <HintPath>..\GameLibs\UnityEngine.GraphToolsFoundationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GridModule">
      <HintPath>..\GameLibs\UnityEngine.GridModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.HotReloadModule">
      <HintPath>..\GameLibs\UnityEngine.HotReloadModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\GameLibs\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\GameLibs\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\GameLibs\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>..\GameLibs\UnityEngine.InputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>..\GameLibs\UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.LocalizationModule">
      <HintPath>..\GameLibs\UnityEngine.LocalizationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.MarshallingModule">
      <HintPath>..\GameLibs\UnityEngine.MarshallingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.NVIDIAModule">
      <HintPath>..\GameLibs\UnityEngine.NVIDIAModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\GameLibs\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PerformanceReportingModule">
      <HintPath>..\GameLibs\UnityEngine.PerformanceReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\GameLibs\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\GameLibs\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ProfilerModule">
      <HintPath>..\GameLibs\UnityEngine.ProfilerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PropertiesModule">
      <HintPath>..\GameLibs\UnityEngine.PropertiesModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing">
      <HintPath>..\GameLibs\UnityEngine.Purchasing.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.AppleCore">
      <HintPath>..\GameLibs\UnityEngine.Purchasing.AppleCore.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.AppleMacosStub">
      <HintPath>..\GameLibs\UnityEngine.Purchasing.AppleMacosStub.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.AppleStub">
      <HintPath>..\GameLibs\UnityEngine.Purchasing.AppleStub.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.Codeless">
      <HintPath>..\GameLibs\UnityEngine.Purchasing.Codeless.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.SecurityCore">
      <HintPath>..\GameLibs\UnityEngine.Purchasing.SecurityCore.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.SecurityStub">
      <HintPath>..\GameLibs\UnityEngine.Purchasing.SecurityStub.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.Stores">
      <HintPath>..\GameLibs\UnityEngine.Purchasing.Stores.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.WinRTCore">
      <HintPath>..\GameLibs\UnityEngine.Purchasing.WinRTCore.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Purchasing.WinRTStub">
      <HintPath>..\GameLibs\UnityEngine.Purchasing.WinRTStub.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
      <HintPath>..\GameLibs\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>..\GameLibs\UnityEngine.ScreenCaptureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SharedInternalsModule">
      <HintPath>..\GameLibs\UnityEngine.SharedInternalsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpatialTracking">
      <HintPath>..\GameLibs\UnityEngine.SpatialTracking.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteMaskModule">
      <HintPath>..\GameLibs\UnityEngine.SpriteMaskModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteShapeModule">
      <HintPath>..\GameLibs\UnityEngine.SpriteShapeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.StreamingModule">
      <HintPath>..\GameLibs\UnityEngine.StreamingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubstanceModule">
      <HintPath>..\GameLibs\UnityEngine.SubstanceModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubsystemsModule">
      <HintPath>..\GameLibs\UnityEngine.SubsystemsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>..\GameLibs\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>..\GameLibs\UnityEngine.TerrainPhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>..\GameLibs\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>..\GameLibs\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\GameLibs\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>..\GameLibs\UnityEngine.TilemapModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TLSModule">
      <HintPath>..\GameLibs\UnityEngine.TLSModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UaaLAnalyticsModule">
      <HintPath>..\GameLibs\UnityEngine.UaaLAnalyticsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\GameLibs\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\GameLibs\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsNativeModule">
      <HintPath>..\GameLibs\UnityEngine.UIElementsNativeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\GameLibs\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UmbraModule">
      <HintPath>..\GameLibs\UnityEngine.UmbraModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UNETModule">
      <HintPath>..\GameLibs\UnityEngine.UNETModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
      <HintPath>..\GameLibs\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsModule">
      <HintPath>..\GameLibs\UnityEngine.UnityAnalyticsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityConnectModule">
      <HintPath>..\GameLibs\UnityEngine.UnityConnectModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityCurlModule">
      <HintPath>..\GameLibs\UnityEngine.UnityCurlModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityTestProtocolModule">
      <HintPath>..\GameLibs\UnityEngine.UnityTestProtocolModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
      <HintPath>..\GameLibs\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>..\GameLibs\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\GameLibs\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>..\GameLibs\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>..\GameLibs\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VehiclesModule">
      <HintPath>..\GameLibs\UnityEngine.VehiclesModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VFXModule">
      <HintPath>..\GameLibs\UnityEngine.VFXModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>..\GameLibs\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VirtualTexturingModule">
      <HintPath>..\GameLibs\UnityEngine.VirtualTexturingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>..\GameLibs\UnityEngine.VRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.WindModule">
      <HintPath>..\GameLibs\UnityEngine.WindModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XR.LegacyInputHelpers">
      <HintPath>..\GameLibs\UnityEngine.XR.LegacyInputHelpers.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>..\GameLibs\UnityEngine.XRModule.dll</HintPath>
    </Reference>
    <Reference Include="websocket-sharp">
      <HintPath>..\GameLibs\websocket-sharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
